### PR TITLE
fix the incorrect constructor initialization

### LINKED ISSUE #365: `ConcreteBuffer::nbytes` goes wrong
[`test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer_from_ndarray`](https://github.com/solvcon/modmesh/blob/ff4b4d654ab9abc53fe4096bf952e67929f972ac/tests/test_buffer.py#L80) fails after PR #363 is merged.  See CI failure for more information at https://github.com/solvcon/modmesh/actions/runs/9537773849/job/26290385018#step:12:98 :

```
  ..\..\..\..\tests\test_buffer.py::ConcreteBufferBasicTC::test_ConcreteBuffer_from_ndarray FAILED [  1%]
  
  ================================== FAILURES ===================================
  ___________ ConcreteBufferBasicTC.test_ConcreteBuffer_from_ndarray ____________
  
  self = <test_buffer.ConcreteBufferBasicTC testMethod=test_ConcreteBuffer_from_ndarray>
  
      def test_ConcreteBuffer_from_ndarray(self):
      
          buf = modmesh.ConcreteBuffer(24)
          self.assertFalse(buf.is_from_python)
      
          ndarr = np.arange(24, dtype='float64').reshape((2, 3, 4))
      
          buf = modmesh.ConcreteBuffer(array=ndarr)
  >       self.assertEqual(ndarr.nbytes, buf.nbytes)
  E       AssertionError: 192 != 0
  
  ..\..\..\..\tests\test_buffer.py:80: AssertionError
```

The failure only happens on Windows, but I guess it could be a random behavior.

---

Ref issue #305

### PR DESCRIPTION
**Pull request by tigercosmos**
fix #365

after allocating the new buffer, the old buffer may be an invalid memory address.

setting `m_begin` and `m_end` before calling `size()`

### CODE REVIEW

File: cpp/modmesh/buffer/ConcreteBuffer.hpp [hunk 1]
```diff
@@ -213,14 +213,13 @@ class ConcreteBuffer
         , m_nbytes(other.m_nbytes)
         , m_data(allocate(other.m_nbytes))
     {
+        m_begin = m_data.get(); // override m_begin and m_end once we have the data
```
Comment (tigercosmos) [inline cpp/modmesh/buffer/ConcreteBuffer.hpp]: need to initialize before the following `size()` call.

Comment (yungyuc) [reply cpp/modmesh/buffer/ConcreteBuffer.hpp]: At some places you wrote "overwrite" and here you write "override" `m_begin` and `m_end`.  Please word consistently.

**Review by yungyuc — CHANGES_REQUESTED** [review]
- [ ] Use consistent wording for "overwrite" and "override".  Choose either one but do not use both interchangeably.

File: cpp/modmesh/buffer/BufferBase.hpp [hunk 2]
```diff
@@ -96,7 +96,9 @@ class BufferBase
 
     BufferBase(int8_t * start, int8_t * end)
         : m_begin(start)
-        , m_end(end){};
+        , m_end(end)
```
Comment (tigercosmos) [inline cpp/modmesh/buffer/BufferBase.hpp:99]: fix the format that was mentioned in the previous PR.

**Comment by tigercosmos** [comment]
@yungyuc  the issues are addressed.

File: cpp/modmesh/buffer/BufferExpander.hpp [hunk 3]
```diff
@@ -75,15 +75,15 @@ class BufferExpander
         : BufferBase<BufferExpander>() // don't delegate m_begin and m_end, which will be overwritten later
         , m_concrete_buffer(clone ? buf->clone() : buf)
     {
-        m_begin = m_concrete_buffer->data(); // override m_begin and m_end once we have the data
+        m_begin = m_concrete_buffer->data(); // overwrite m_begin and m_end once we have the data
```
Comment (tigercosmos) [inline cpp/modmesh/buffer/BufferExpander.hpp:78]: fix to "overwrite" for all

**Comment by yungyuc** [comment]
Thanks, @tigercosmos , especially for squashing all intermediate changesets.
