### PR TITLE
Fix the initializer from numpy to SimpleArray

### LINKED ISSUE #527: Bug: `SimpleArrayMixinCalculators` needs to handle non-c-contiguous memory buffer
If the array is not c-contiguous, the return values of the functions in `class SimpleArrayMixinCalculators;` are wrong.

In other words, it is necessary to fix the function `SimpleArrayMixinCalculators::min()`, `SimpleArrayMixinCalculators::max()`, `SimpleArrayMixinCalculators::sum()`, `SimpleArrayMixinCalculators::abs()`.

For example:

Unittest:
```python3
    def test_sum2(self):

        nparr = np.arange(24, dtype='float64').reshape((2, 3, 4))
        nparr = nparr[:,:,::2] ## Slicing
        sarr = modmesh.SimpleArrayFloat64(array=nparr) 
        npsum = nparr.sum()
        ssum = sarr.sum()
        self.assertEqual(npsum, ssum)
```

Source code of `sum()`:
```c++
    value_type sum() const
    {
        value_type initial;
        if constexpr (is_complex_v<value_type>)
        {
            initial = value_type();
        }
        else
        {
            initial = 0;
        }

        auto athis = static_cast<A const *>(this);
        if constexpr (!std::is_same_v<bool, std::remove_const_t<value_type>>)
        {
            for (size_t i = 0; i < athis->size(); ++i)
            {
                initial += athis->data(i);
            }
        }
        else
        {
            for (size_t i = 0; i < athis->size(); ++i)
            {
                initial |= athis->data(i);
            }
        }
        return initial;
    }
```

Console log:
```console

self = <test_buffer.SimpleArrayCalculatorsTC testMethod=test_sum2>

    def test_sum2(self):
    
        nparr = np.arange(24, dtype='float64').reshape((2, 3, 4))
        nparr = nparr[:,:,::2]
        sarr = modmesh.SimpleArrayFloat64(array=nparr)
        npsum = nparr.sum()
        ssum = sarr.sum()
>       self.assertEqual(npsum, ssum)
E       AssertionError: np.float64(132.0) != 66.0

tests/test_buffer.py:962: AssertionError
================================================================================================================================================================================== short test summary info ==================================================================================================================================================================================
FAILED tests/test_buffer.py::SimpleArrayCalculatorsTC::test_sum2 - AssertionError: np.float64(132.0) != 66.0
```

### PR DESCRIPTION
**Pull request by ThreeMonth03**
In this pull request, I fix the initializer in SimpleArray. 
This modification will help us solve the issue #527.

### CODE REVIEW

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 1]
```diff
@@ -834,8 +815,18 @@ class SimpleArray
...
+    size_t nbytes() const noexcept { return size() * ITEMSIZE; }
+    size_t size() const noexcept
+    {
+        size_t size = 1;
+        for (size_t it = 0; it < m_shape.size(); ++it)
+        {
+            size *= m_shape[it];
+        }
+        return size;
+    }
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Differentiate the `buffer_size()`, `size()`, `buffer_nbytes()` and `nbytes()`.
In numpy, the function `size()` and `nbytes()` is calculated by shape.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 2]
```diff
@@ -1090,11 +1081,11 @@ class SimpleArray
...
             throw std::out_of_range(Formatter() << "SimpleArray: index " << it << " < -nghost: " << -static_cast<ssize_t>(m_nghost));
         }
-        if (it >= static_cast<ssize_t>(size() - m_nghost))
+        if (it >= static_cast<ssize_t>(buffer_size() - m_nghost))
         {
             throw std::out_of_range(
-                Formatter() << "SimpleArray: index " << it << " >= " << size() - m_nghost
-                            << " (size: " << size() << " - nghost: " << m_nghost << ")");
+                Formatter() << "SimpleArray: index " << it << " >= " << buffer_size() - m_nghost
+                            << " (buffer size: " << buffer_size() << " - nghost: " << m_nghost << ")");
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp]: This condition is calculated by the `buffer_size()`, so I fix it.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp [hunk 3]
```diff
@@ -87,10 +88,49 @@ class MODMESH_PYTHON_WRAPPER_VISIBILITY WrapSimpleArray
...
+                             * For example, the following code will create a loop:
+                             * nparr = np.arange(24, dtype='float64').reshape((2, 3, 4))
+                             * nparr = nparr[::2, ::2, ::2]
+                             */
+                            if (next.ptr() == owner.ptr())
+                            {
+                                break;
+                            }
+                            owner = next;
+                        }
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:117]: The while loop will take the buffer and metadata of the root numpy array.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp [hunk 4]
```diff
@@ -87,10 +88,49 @@ class MODMESH_PYTHON_WRAPPER_VISIBILITY WrapSimpleArray
...
+                        if (offset_bytes < 0)
+                        {
+                            throw std::runtime_error("Unexpected negative offset!");
+                        }
+                        const size_t true_owner_nbytes = owner.nbytes();
+                        const size_t view_nbytes = true_owner_nbytes - static_cast<size_t>(offset_bytes);
+                        auto remover = std::make_unique<ConcreteBufferNdarrayRemover>(owner);
+                        const std::shared_ptr<ConcreteBuffer> buffer =
+                            ConcreteBuffer::construct(
+                                view_nbytes,
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:131]: The buffer size should consider the offset.

File: tests/test_buffer.py [hunk 5]
```diff
@@ -500,6 +502,8 @@ def test_SimpleArray_from_ndarray(self):
 
         py_sarr = modmesh.SimpleArrayFloat64(array=np_sarr)
         self.assertTupleEqual(shape, py_sarr.shape)
+        self.assertEqual(np_sarr.nbytes, py_sarr.nbytes)
+        self.assertEqual(np_sarr.size, py_sarr.size)
```
Comment (ThreeMonth03) [inline tests/test_buffer.py:506]: Ensure that the information of `nbytes` and `size` are right when the SimpleArray is not sliced.

File: tests/test_buffer.py [hunk 6]
```diff
@@ -524,6 +528,8 @@ def test_SimpleArray_from_ndarray_slice(self):
             for j in range(4):
                 for k in range(6):
                     self.assertEqual(parr[i, j, k], sarr[i, j, k])
+        self.assertEqual(parr.nbytes, sarr.nbytes)
+        self.assertEqual(parr.size, sarr.size)
```
Comment (ThreeMonth03) [inline tests/test_buffer.py:532]: Ensure that the information of nbytes and size are right when the SimpleArray is sliced.

File: tests/test_buffer.py [hunk 7]
```diff
@@ -1061,6 +1074,13 @@ def test_average(self):
         savg = sarr.average()
         self.assertEqual(npavg, savg)
 
+        nparr = np.arange(24, dtype='float64').reshape((2, 3, 4))
+        nparr = nparr[::2, ::2, ::2]
+        sarr = modmesh.SimpleArrayFloat64(array=nparr)
+        npavg = np.average(nparr)
+        savg = sarr.average()
+        self.assertEqual(npavg, savg)
```
Comment (ThreeMonth03) [inline tests/test_buffer.py:1082]: Add the unittest of the statistic operation to ensure that the sliced array works well.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 8]
```diff
@@ -152,11 +152,7 @@ class SimpleArrayMixinCalculators
     value_type median() const
     {
         auto athis = static_cast<A const *>(this);
-        size_t n = 1;
-        for (size_t i = 0; i < athis->ndim(); ++i)
-        {
-            n *= athis->shape(i);
-        }
+        size_t n = athis->size();
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Use member function `size()`.

**Review by ThreeMonth03 — COMMENTED** [review]
@yungyuc You can review this pull request if you are available. Thank you.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 8 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp]: Good catch.  Please also make it `const`.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 9]
```diff
@@ -834,8 +815,18 @@ class SimpleArray
 
     explicit operator bool() const noexcept { return bool(m_buffer) && bool(*m_buffer); }
 
-    size_t nbytes() const noexcept { return m_buffer ? m_buffer->nbytes() : 0; }
-    size_t size() const noexcept { return nbytes() / ITEMSIZE; }
+    size_t buffer_nbytes() const noexcept { return m_buffer ? m_buffer->nbytes() : 0; }
```
Comment (yungyuc) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Do not implement `buffer_nbytes()` and use `buffer().nbytes()` instead.  Note that `buffer()` is a public member function.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 10]
```diff
@@ -834,8 +815,18 @@ class SimpleArray
...
+    size_t buffer_size() const noexcept { return buffer_nbytes() / ITEMSIZE; }
```
Comment (yungyuc) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Do not implement `buffer_size()`.  Use `buffer().size()/ITEMSIZE` instead.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 2 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp]: The condition should continue to use the buffer size, but use `buffer().size()` instead of the unnecessary helper function.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 1 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp]: Please add code comment here to say this is to match numpy implementation.

I like the previous `SimpleArray` implementation more, but matching numpy behavior here will make everyone's life easier.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp [hunk 11]
```diff
@@ -87,10 +88,49 @@ class MODMESH_PYTHON_WRAPPER_VISIBILITY WrapSimpleArray
                         const bool is_c_contiguous = (arr_in.flags() & py::array::c_style) == py::array::c_style;
                         const bool is_f_contiguous = (arr_in.flags() & py::array::f_style) == py::array::f_style;
 
-                        std::shared_ptr<ConcreteBuffer> const buffer = ConcreteBuffer::construct(
-                            arr_in.nbytes(),
-                            arr_in.mutable_data(),
-                            std::make_unique<ConcreteBufferNdarrayRemover>(arr_in));
+                        py::array owner = arr_in;
+                        /*
+                         * In the following document, it introduces the base object in ndarray.
```
Comment (yungyuc) [inline cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:93]: Good note.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp [hunk 12]
```diff
@@ -87,10 +88,49 @@ class MODMESH_PYTHON_WRAPPER_VISIBILITY WrapSimpleArray
...
+                            }
+                            owner = next;
+                        }
+
+                        char * base_ptr = static_cast<char *>(owner.mutable_data());
+                        char * view_ptr = static_cast<char *>(arr_in.mutable_data());
+                        const ptrdiff_t offset_bytes = view_ptr - base_ptr;
+                        if (offset_bytes < 0)
+                        {
+                            throw std::runtime_error("Unexpected negative offset!");
```
Comment (yungyuc) [inline cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:124]: Is it possible to add a unit test checking for this error message?

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp (hunk 4 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:131]: When there is time, I'd like to learn your thoughts on the design of remover.

File: tests/test_buffer.py [hunk 13]
```diff
@@ -320,7 +320,7 @@ def test_SimpleArray_ghost_1d(self):
 
         with self.assertRaisesRegex(
                 IndexError,
-                r"SimpleArray: index 14 >= 14 \(size: 24 - nghost: 10\)"
+                r"SimpleArray: index 14 >= 14 \(buffer size: 24 - nghost: 10\)"
```
Comment (yungyuc) [inline tests/test_buffer.py:323]: Good change of the message.

File: tests/test_buffer.py (hunk 5 above)
Comment (yungyuc) [reply tests/test_buffer.py:506]: Good check.

File: tests/test_buffer.py (hunk 7 above)
Comment (yungyuc) [reply tests/test_buffer.py:1082]: Beautiful.

**Review by yungyuc — CHANGES_REQUESTED** [review]
- [x] Add constness: `size_t n = athis->size();` to `size_t const n = athis->size();`  Note that there are more than 1 occurrence.
- [x] Add code comment here for matching the `size()` and `nbytes()` behavior with numpy.

Don't add the following unnecessary `SimpleArray` member functions.  They are duplicate code confusing people without adding value.

- [x] Do not implement `buffer_nbytes()` and use `buffer().nbytes()` instead.  Note that `buffer()` is a public member function.
- [x] Do not implement `buffer_size()`.  Use `buffer().size()/ITEMSIZE` instead.

Additional item:

- [ ] Add an issue to track profiling the statistical functions and comparing with numpy.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp (hunk 12 above)
Comment (ThreeMonth03) [reply cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:124]: Here is the suggestion by gpt.
https://chatgpt.com/share/682c87e3-4d40-800a-807d-84e761427b3d
It seems that we should implement the data structure like np.array.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 14]
```diff
@@ -205,11 +201,7 @@ class SimpleArrayMixinCalculators
     real_type var(size_t ddof) const
     {
         auto athis = static_cast<A const *>(this);
-        size_t n = 1;
-        for (size_t i = 0; i < athis->ndim(); ++i)
-        {
-            n *= athis->shape(i);
-        }
+        const size_t n = athis->size();
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp:204]: Add `const`.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 15]
```diff
@@ -834,8 +815,23 @@ class SimpleArray
...
 
-    size_t nbytes() const noexcept { return m_buffer ? m_buffer->nbytes() : 0; }
-    size_t size() const noexcept { return nbytes() / ITEMSIZE; }
+    /*
+     * In the following numpy documentaions,
+     * `nbytes()` and `size()` are calculated based on the number of the elements.
+     * 1. https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.size.html
+     * 2. https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.nbytes.html
+     * SimpleArray matchs the behavior of numpy.ndarray.
+     */
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Add comments.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 16]
```diff
@@ -834,8 +815,23 @@ class SimpleArray
...
+    size_t nbytes() const noexcept { return size() * ITEMSIZE; }
+    size_t size() const noexcept
+    {
+        size_t size = 1;
+        for (size_t it = 0; it < m_shape.size(); ++it)
+        {
+            size *= m_shape[it];
+        }
+        return size;
+    }
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp]: Remoe the duplicated function `buffer_size()` and `buffer_nbytes()`.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 17]
```diff
@@ -1090,11 +1086,11 @@ class SimpleArray
         {
             throw std::out_of_range(Formatter() << "SimpleArray: index " << it << " < -nghost: " << -static_cast<ssize_t>(m_nghost));
         }
-        if (it >= static_cast<ssize_t>(size() - m_nghost))
+        if (it >= static_cast<ssize_t>((buffer().nbytes() / ITEMSIZE) - m_nghost))
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp:1088]: https://github.com/solvcon/modmesh/blob/6b1a4b953aa11f3975f7c0462022be36da8d20c4/cpp/modmesh/buffer/BufferBase.hpp#L45-L49
In `class buffebase;`, the function `size()` is `nbytes() / sizeof(int8_t`, so I don't use `buffer().size()` here.

**Review by ThreeMonth03 — COMMENTED** [review]
@yungyuc You could review this pull request when you are available. Thank you.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp (hunk 12 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:124]: It is never a good idea to directly use AI assistant as your thought.  It is fine to use AI assistant, but do verify and organize the results before making response.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 15 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp]: Please move the comment to be in front of `size()`, and use doxygen format:

```cpp
    /**
     * In the following numpy documentaions,
     * `nbytes()` and `size()` are calculated based on the number of the elements.
     * 1. https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.size.html
     * 2. https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.nbytes.html
     * SimpleArray matchs the behavior of numpy.ndarray.
     */
```

It is not necessary to explain `nbytes()` since it depends on `size()`.

File: cpp/modmesh/buffer/SimpleArray.hpp (hunk 16 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/SimpleArray.hpp]: This is good.

**Review by yungyuc — CHANGES_REQUESTED** [review]
- [x] Carefully analyze the way to test for the error message, or make it clear why you do not want to analyze.
- [x] Beautify comments for `SimpleArray::size()`.

File: cpp/modmesh/buffer/SimpleArray.hpp [hunk 18]
```diff
@@ -834,8 +815,22 @@ class SimpleArray
...
 
-    size_t nbytes() const noexcept { return m_buffer ? m_buffer->nbytes() : 0; }
-    size_t size() const noexcept { return nbytes() / ITEMSIZE; }
+    size_t nbytes() const noexcept { return size() * ITEMSIZE; }
+    /**
+     * In the following numpy documentaions,
+     * `size()` are calculated based on the number of the elements.
+     * https://numpy.org/doc/2.2/reference/generated/numpy.ndarray.size.html
+     * SimpleArray matchs the behavior of numpy.ndarray.
+     */
```
Comment (ThreeMonth03) [inline cpp/modmesh/buffer/SimpleArray.hpp:824]: - [x] Move the comment in front of `size()`.
 - [x] Use the doxygen format.
 - [x] Remove the comment about `nbytes()`.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp (hunk 12 above)
Comment (ThreeMonth03) [reply cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:124]: I think it is not possile to add a unit test checking for this error message.
In [pybind11 documentation](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#arrays), it says:
```
By exchanging py::buffer with py::array in the above snippet, we can restrict the function so that it only accepts NumPy arrays (rather than any type of Python object satisfying the buffer protocol).
```
The initializer only accepts the numpy array, but it is impossible to throw the error message with the common numpy array.

**Review by ThreeMonth03 — COMMENTED** [review]
- [x] Modify the comment.
- [x] Explain why I don't check the error message.

File: cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp (hunk 12 above)
Comment (yungyuc) [reply cpp/modmesh/buffer/pymod/wrap_SimpleArray.cpp:124]: I think you meant to say it is impossible to trigger the exception with a normally created ndarray from Python whose `offset_bytes < 0`.  In that case it makes sense.  Let me know if my understanding is incorrect.

**Review by yungyuc — APPROVED** [review]
Beautiful
